---

Description: Static website on S3

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      BucketName: aws-playground-logs
      AccessControl: LogDeliveryWrite
      Tags:
        - Key: BucketType
          Value: logs

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      BucketName: aws-playground-site
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: aws-playground-site
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error/index.html
      Tags:
        - Key: BucketType
          Value: public-site

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt SiteOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Join [ '', [ !GetAtt StaticSiteBucket.Arn, '/*' ] ]

  SiteOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: AWS Playground Origin access identity

  SiteCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt StaticSiteBucket.DomainName
          Id: SiteS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${SiteOriginAccessIdentity}
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: SiteS3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
      Tags:
        - Key: CloudFrontDistribution
          Value: public-site

Outputs:
  StaticSiteBucket:
    Description: Bucket name of static site
    Value: !Ref StaticSiteBucket
  CloudfrontUrl:
    Description: Url to access site
    Value: !GetAtt SiteCloudfront.DomainName
