---
Parameters:
  VPCCidr:
    Description: Enter VPC IP range for VPC
    Type: String
    Default: 10.0.0.0/16

Description: AWS Playground VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: aws-playground-vpc

  VPCCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
